name: Print Commit Message

on:
  push:   # Trigger this workflow on every push to any branch
    branches:
      - '**'

jobs:
  print-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print latest commit message
        run: |
          echo "Commit message:"
          git log -1 --pretty=%B


