name: "Hello World workflow"

# Triggeres when any thing happen or master or prod branches
on: 
  push:
    branches:
      - master
      - production

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "Hello World"
