name: Manual Dispatch Workflow

on:
  push:
    branches:
      - main

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run manual job
        run: echo "This workflow was triggered manually."
